spring:
  redis:
    host: 127.0.0.1
    password:
    port: 6379
    database: 0
    pool:

    timeout: 1000
    jedis:
      pool:
        max-idle: 10

  datasource:
    url: jdbc:mysql://localhost:3306/mydb?characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=GMT%2B8
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: lxm
    password: 123456
    virtual-host: /springDemo

server:
  port: 8080




