spring:
  redis:
    host: 127.0.0.1
    password:
    port: 6379
    database: 0
    pool:
      max-active: 10
    timeout: 1000

  datasource:
    url: jdbc:mysql://localhost:3306/test?characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=GMT%2B8
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver

server:
  port: 8080




