spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=GMT%2B8
    username: root
    password:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
server:
  port: 8080



