server:
  context-path: /springDemo

mybatis:
  typeAliasesPackage: lxm.model
  mapperLocations: classpath:mapper/*.xml

spring:
  application:
    name: test
  profiles:
    active: testing

logging:
  config: classpath:log4j2.yml